### ISSUE TITLE
Problems with compilation?

### ISSUE THREAD

**Issue by Uko** [SquareBracketAssociates/BuildingUIWithSpec#11] opened 2016-07-23 16:32 UTC
Hi, I've followed the readme:
- clone
- run `./subdownload.sh`
- run `./compile.sh`     _<- this gets stuck_

looks like the script gets stuck on `./pillar export`

**Comment by jfabry** [comment] 2016-07-23 18:10
This is probably due to the changes in Pillar for the latest release. Thanks for notifying! The CI still seems to work OK though, so you can get the .pdfs from there for now.

@DamienCassou can you tell me what the required magic is to make this work again?

**Comment by Uko** [comment] 2016-07-23 18:15
@jfabry I had no idea that there is a CI job :)

**Comment by Uko** [comment] 2016-07-23 19:44
But the CI artifacts do not contain any pdfs/html/whatever. Is this how it should be?

**Comment by jecisc** [comment] 2016-07-23 21:31
@Uko I see pdfs:

https://ci.inria.fr/pharo-contribution/view/Books/job/BuildingUIWithSpec/lastSuccessfulBuild/artifact/book-result/SpecBooklet.pdf

**Comment by Uko** [comment] 2016-07-23 21:51
Oh, pardon me please, I didn't know that the result is in the `book-result` directory. thank you!

**Comment by jecisc** [comment] 2016-07-23 21:54
But, as you said we see that the last build is stuck. I think that @YannDub and/or @ThibaultAr will be able to help next week :)

**Comment by YannDub** [comment] 2016-07-23 22:08
I will take a look on monday. Pillar no longer compiles files, we use now a Makefile (EnterprisePharo was updated)

**Comment by YannDub** [comment] 2016-07-26 14:18
I propose an update in the PR : #12

**Comment by jfabry** [comment] 2016-07-27 20:16
@YannDub  The update is not working on my machine :-( Please have a look because like this I cannot do any work on the book.

After a subdownload.sh that finishes without errors:

```
Makivi:BuildingUIWithSpec jfabry$ make chapters
mkdir -p ./book-result
find . -type d -path ./book-result -prune -o -wholename "*/figures" -exec cp {} --parents -r ./book-result \;
cp: ./AdvancedWidgets/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./DynamicSpec/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./FirstContact/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./LayoutsContruction/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./ManagingWindow/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./material/example/CalculatorTutorial/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./material/partRedacted/old/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./Reuse/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./SpecInternals/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./ThreePillarsOfSpec/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./TipsAndTricks/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp -r support/ ./book-result
cp .latexmkrc ./book-result
./pillar export --to="latex:sbabook" --path="AdvancedWidgets/AdvancedWidgets.pillar" AdvancedWidgets/AdvancedWidgets.pillar

*** Warning: PRReferenceNotFound: Can't find anchor named 'ex_popup_initializewidget'

*** Warning: PRReferenceNotFound: Can't find anchor named 'ex_radio_initializepresenter'
./mustache --data=book-result/AdvancedWidgets/AdvancedWidgets.tex.json --template=./support/templates/chapter.latex.template > book-result/AdvancedWidgets/AdvancedWidgets.tex
FileDoesNotExist: File @ /Users/jfabry/Research/Books/BuildingUIWithSpec/book-result/AdvancedWidgets/AdvancedWidgets.tex.json
FileHandle>>streamError
FileHandle>>readStream
FileSystem>>readStreamOn:
FileReference>>readStream
FileReference(AbstractFileReference)>>readStreamDo:
FileReference(AbstractFileReference)>>contents
MustacheCommandLineHandler>>activate
MustacheCommandLineHandler class(CommandLineHandler class)>>activateWith:
[ aCommandLinehandler activateWith: commandLine ] in PharoCommandLineHandler(BasicCommandLineHandler)>>activateSubCommand: in Block: [ aCommandLinehandler activateWith: commandLine ]
BlockClosure>>on:do:
PharoCommandLineHandler(BasicCommandLineHandler)>>activateSubCommand:
PharoCommandLineHandler(BasicCommandLineHandler)>>handleSubcommand
PharoCommandLineHandler(BasicCommandLineHandler)>>handleArgument:
[ self
    handleArgument:
        (self arguments
            ifEmpty: [ '' ]
            ifNotEmpty: [ :arguments | arguments first ]) ] in PharoCommandLineHandler(BasicCommandLineHandler)>>activate in Block: [ self...
BlockClosure>>on:do:
PharoCommandLineHandler(BasicCommandLineHandler)>>activate
PharoCommandLineHandler>>activate
PharoCommandLineHandler class(CommandLineHandler class)>>activateWith:
[ super activateWith: aCommandLine ] in PharoCommandLineHandler class>>activateWith: in Block: [ super activateWith: aCommandLine ]
NonInteractiveUIManager(UIManager)>>defer:
PharoCommandLineHandler class>>activateWith:
[ aCommandLinehandler activateWith: commandLine ] in BasicCommandLineHandler>>activateSubCommand: in Block: [ aCommandLinehandler activateWith: commandLine ]
BlockClosure>>on:do:
BasicCommandLineHandler>>activateSubCommand:
BasicCommandLineHandler>>handleSubcommand
BasicCommandLineHandler>>handleArgument:
[ self
    handleArgument:
        (self arguments
            ifEmpty: [ '' ]
            ifNotEmpty: [ :arguments | arguments first ]) ] in BasicCommandLineHandler>>activate in Block: [ self...
BlockClosure>>on:do:
BasicCommandLineHandler>>activate
[ self new activate ] in BasicCommandLineHandler class>>startUp: in Block: [ self new activate ]
make: *** [book-result/AdvancedWidgets/AdvancedWidgets.tex] Error 1

```

**Comment by jfabry** [comment] 2016-07-27 22:12
@YannDub Same problem on the CI server. See https://ci.inria.fr/pharo-contribution/view/Books/job/BuildingUIWithSpec/21/console

**Comment by YannDub** [comment] 2016-07-28 08:13
The problem is solved, it was because I've corrected a little bug yesterday in Pillar and I've removed a property on the command line handler.

I don't know why the build crash again.

**Comment by jfabry** [comment] 2016-07-28 17:48
Still not working on my computer. @YannDub any ideas?

```
Makivi:BuildingUIWithSpec jfabry$ make chapters
git submodule update --init
mkdir -p ./book-result
find . -type d -path ./book-result -prune -o -wholename "*/figures" -exec cp {} --parents -r ./book-result \;
cp: ./AdvancedWidgets/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./DynamicSpec/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./FirstContact/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./LayoutsContruction/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./ManagingWindow/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./material/example/CalculatorTutorial/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./material/partRedacted/old/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./Reuse/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./SpecInternals/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./ThreePillarsOfSpec/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp: ./TipsAndTricks/figures is a directory (not copied).
cp: --parents: No such file or directory
cp: -r: No such file or directory
cp -r support/ ./book-result
cp .latexmkrc ./book-result
./pillar export --to="latex:sbabook" --outputFile=AdvancedWidgets/AdvancedWidgets AdvancedWidgets/AdvancedWidgets.pillar

*** Warning: PRReferenceNotFound: Can't find anchor named 'ex_popup_initializewidget'

*** Warning: PRReferenceNotFound: Can't find anchor named 'ex_radio_initializepresenter'
./mustache --data=book-result/AdvancedWidgets/AdvancedWidgets.tex.json --template=./support/templates/chapter.latex.template > book-result/AdvancedWidgets/AdvancedWidgets.tex
latexmk -f -cd -use-make -pdf book-result/AdvancedWidgets/AdvancedWidgets.tex
Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.
Latexmk: Changing directory to 'book-result/AdvancedWidgets/'
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'lualatex --file-line-error --interaction=nonstopmode --halt-on-error  -recorder  "AdvancedWidgets.tex"'
------------
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238) 
 restricted \write18 enabled.
(./AdvancedWidgets.tex
LaTeX2e <2015/10/01> patch level 2
Babel <3.9n> and hyphenation patterns for 79 languages loaded.

! LaTeX Error: File `root/support/latex/sbabook/sbabook.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
./AdvancedWidgets.tex:5: Emergency stop.
<read *> 

l.5   \usepackage
               {import}
 190 words of node memory still in use:
   31 glue_spec, 1 if_stack, 1 dir nodes
   avail lists: 2:11,3:1
./AdvancedWidgets.tex:5:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on AdvancedWidgets.log.
Latexmk: Missing input file: 'root/support/latex/sbabook/sbabook.cls' from line
  '! LaTeX Error: File `root/support/latex/sbabook/sbabook.cls' not found.'
Latexmk: 'pdflatex': source file 'root/support/latex/sbabook/sbabook.cls' doesn't exist. I'll try making it...
------------
Running 'make "root/support/latex/sbabook/sbabook.cls"'
------------
make[1]: *** No rule to make target `root/support/latex/sbabook/sbabook.cls'.  Stop.
Failure to make 'AdvancedWidgets.pdf'
Latexmk: Errors, in force_mode: so I tried finishing targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Undoing directory change
make: *** [book-result/AdvancedWidgets/AdvancedWidgets.pdf] Error 12
Makivi:BuildingUIWithSpec jfabry$ 

```

**Comment by YannDub** [comment] 2016-07-28 18:47
Maybe you need to change all the `-r` in `copySupport.mk` by `-R`. For me, it change nothing but for you it could be the solution.

**Comment by jfabry** [comment] 2016-07-29 01:56
@YannDub Sorry that does not work, and is not really a surprise to me because the problem is that 

```
! LaTeX Error: File `root/support/latex/sbabook/sbabook.cls' not found.
```

 I have `support/latex/sbabook/sbabook.cls` instead of `root/support/latex/sbabook/sbabook.cls`

**Comment by jfabry** [comment] 2016-07-29 19:56
Closing this one because more detail is in issue #13

**Closed as completed by jfabry** 2016-07-29 19:56 UTC
